export type InlandTaxDetail = {
  Code: string;
  Label: string;
  Amount: string;
  Currency: string;
};

export type DividendEntry = {
  ID: number;
  UserID: number;
  DepotID: number;
  SecurityID: number;
  PayDate: string;
  ExDate: string;
  SecurityName: string;
  SecurityISIN: string;
  SecurityWKN: string;
  SecuritySymbol: string;
  Quantity: string;
  DividendPerUnitAmount: string;
  DividendPerUnitCurrency: string;
  FXRateLabel: string;
  FXRate: string;
  GrossAmount: string;
  GrossCurrency: string;
  PayoutAmount: string;
  PayoutCurrency: string;
  WithholdingTaxCountryCode: string;
  WithholdingTaxPercent: string;
  WithholdingTaxAmount: string;
  WithholdingTaxCurrency: string;
  WithholdingTaxAmountCredit: string;
  WithholdingTaxAmountCreditCurrency: string;
  WithholdingTaxAmountRefundable: string;
  WithholdingTaxAmountRefundableCurrency: string;
  ForeignFeesAmount: string;
  ForeignFeesCurrency: string;
  Note: string;
  InlandTaxAmount: string;
  InlandTaxCurrency: string;
  InlandTaxDetails: InlandTaxDetail[];
  CalcGrossAmountBase: string;
  CalcAfterWithholdingAmountBase: string;
  CreatedAt: number;
  UpdatedAt: number;
  [key: string]: unknown;
};

export type CreateDividendEntryPayload = {
  DepotID: number;
  SecurityID: number;
  PayDate: string;
  ExDate: string;
  SecurityName: string;
  SecurityISIN: string;
  SecurityWKN: string;
  SecuritySymbol: string;
  Quantity: string;
  DividendPerUnitAmount: string;
  DividendPerUnitCurrency: string;
  FXRateLabel: string;
  FXRate: string;
  GrossAmount: string;
  GrossCurrency: string;
  PayoutAmount: string;
  PayoutCurrency: string;
  WithholdingTaxCountryCode: string;
  WithholdingTaxPercent: string;
  WithholdingTaxAmount: string;
  WithholdingTaxCurrency: string;
  WithholdingTaxAmountCredit: string;
  WithholdingTaxAmountCreditCurrency: string;
  WithholdingTaxAmountRefundable: string;
  WithholdingTaxAmountRefundableCurrency: string;
  ForeignFeesAmount: string;
  ForeignFeesCurrency: string;
  Note: string;
  InlandTaxDetails: InlandTaxDetail[];
  InlandTaxAmount?: string;
  InlandTaxCurrency?: string;
};

export type UpdateDividendEntryPayload = CreateDividendEntryPayload & {
  ID: number;
};
